### ISSUE TITLE
Tests only pass with arrow function not an anonymous function for setTimeout()

### ISSUE THREAD

**Issue by genericlady** [learn-co-curriculum/react-events-in-detail-lab#10]
@Lukeghenco 
```javascript
  handleClick(event) {
    event.persist();
    setTimeout(() => {
      this.props.onDelayedClick(event);
    }, this.props.delay);
  }
```

but in docs for setTimeout this is how this lab would be solved but it's failing.

```javascript
  handleClick(event) {
    event.persist();
    setTimeout(function() {
      this.props.onDelayedClick(event);
    }, this.props.delay);
  }
```

**Comment by Lukeghenco** [comment]
@genericlady the second option with an anonymous function would require you to use `bind(this)` or alias `this` like `const self = this`. tTis is an issue with scoping not it being an arrow function required for the test.
