### ISSUE TITLE
wording confusing

### ISSUE THREAD

**Issue by georgelgore** [learn-co-curriculum/react-events-in-detail-lab#13]
the wording for coordinates button #2 is very confusing. The words "takes in" makes it sound like it should be entered as an argument to a method.

**Comment by georgelgore** [comment]
also the wording is confusing in general for this entire section

**Comment by georgelgore** [comment]
in addition the description asks for the method to be named setTimeOut but the test is looking for setTimeout.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @georgelgore.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
