### ISSUE TITLE
Poor instructions

### ISSUE THREAD

**Issue by dkStephanos** [learn-co-curriculum/react-events-in-detail-lab#14]
The delayedButton instruction are not clear, and with limited test output, are very difficult to translate into the desired outcome. There is also no solution present.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @dkStephanos.

We have updated and clarified the instructions and updated the tests and started code for this lab. We've also added in the missing solution branch.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
