### ISSUE TITLE
What is the purpose of this lab?

### ISSUE THREAD

**Issue by Ary770** [learn-co-curriculum/react-events-in-detail-lab#15]
Honestly, I don't feel I'm learning how to use React! And it's very frustrating.

I completed the lab, but have no understanding of what the component is supposed to do! Especially when I can't test the app in the browser.

I feel I'm executing isolated tasked without properly understanding how they work in the big picture.

I've decided to take a React course on Udemy and then come back to complete these lessons and labs. Hopefully then I'll learn how to use React properly...

I apologize for all the complains but after knowing and experiencing how you guys can deliver amazing curriculum (as was the case with Ruby, Rails, even the JavaScript track) this track is really disappointing...

**Comment by maxwellbenton** [comment]
Thank you for providing this feedback, @Ary770.

We have updated the content of this lab to clarify it and are also in the testing phase of a new React lesson track that is designed to provide a clearer, improved experience.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.
