### ISSUE TITLE
When?     this.props.onReceiveCoordinates([event.clientX, event.clientY]);

### ISSUE THREAD

**Issue by rogercodes1** [learn-co-curriculum/react-events-in-detail-lab#16]
this.props.onReceiveCoordinates([event.clientX, event.clientY]);
When do we learnt about cllientX or where are we to perceive to get this information from? Seems to be a lab or something missing to explain this.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @rogercodes1 .

We have updated the materials to include a brief intro to clientX and clientY and provided links for further reading to help clarify.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
