### ISSUE TITLE
readme is unclear on functions defined in test suite

### ISSUE THREAD

**Issue by tpetersen0308** [learn-co-curriculum/react-events-in-detail-lab#17]
This is very unclear in the readme (as are many other things), but onReceiveCoordinates and onDelayedClick are functions that are defined _in the test suite_ and passed in as props when the tests are run. Students do not need to define these as props in their component files, and this should be made clear in the readme, especially given how uninformative the error messages in the tests are.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @tpetersen0308 .

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
