### ISSUE TITLE
Passing Written Tests, Browser Errors

### ISSUE THREAD

**Issue by mekowalski** [learn-co-curriculum/react-events-in-detail-lab#20]
Hello!  I wanted to bring awareness to this lab.  I was able to pass the tests that were written for the lab but I had errors in the browser when I actually used the the buttons(to click them) and see their action.

I also noticed that the two functions `onReceiveCoordinates` and `onDelayedClick` are part of the tests but nowhere in my code did I define these functions.  I assume this may be why I am receiving browser errors overall.

Since passing the tests I decided to move on because I couldn't linger any longer on a lab.  I did want to make sure this was looked at though.  I provided the browser errors I received  for both functions and my passing tests in the console.

Happy coding
Malind

![ondelayedclick](https://user-images.githubusercontent.com/15252624/50366175-6eb0d900-0535-11e9-8d7f-3ab58e8b1c5a.png)
![onreceivecoordinates](https://user-images.githubusercontent.com/15252624/50366176-6eb0d900-0535-11e9-8cd2-b05bb8cbd16e.png)
![consoletests](https://user-images.githubusercontent.com/15252624/50366181-76707d80-0535-11e9-8751-e60ee96822a4.png)

**Comment by maxwellbenton** [comment]
Hi @mekowalski,

Thank you for spotting this and bringing it to our attention. We were unable to replicate the error you received, but we have updated the readme to provide clearer instructions. The functions `onReceiveCoordinates` and `onDelayedClick` are provided in `index.js` at the beginining of the lab.

We apologize for any frustration this lab may have caused.  Thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
