### ISSUE TITLE
https://learning.flatironschool.com/courses/1883/assignments/125694?module_item_id=259619

### ISSUE THREAD

**Issue by LGmedia954** [learn-co-curriculum/react-events-in-detail-lab#26]
Two Flatiron TC just confirmed this lab is not working properly. Student is using Google Chrome. The React rendering is not visible despite the compiling correctly.

**Comment by ihollander** [comment]
Hi @LGmedia954, I looked into this issue for you and it doesn't appear that this is related to any problems with the lab code. I looked at your forked repository and was able to run the lab just fine, and view the output in the browser after running `npm install && npm start`:

<img width="993" alt="react-events-in-detail-lab" src="https://user-images.githubusercontent.com/39830572/145024206-b947b8b4-aa52-40e3-8dd9-0ab479816ee5.png">

Based on this, it appears this issue may be in your local environment (for example, having another application running on port 3000, or an issue with your browser), so I'm closing this issue. Best of luck with the rest of the course!
