### ISSUE TITLE
just a suggestion for this lab

### ISSUE THREAD

**Issue by bmolina-nyc** [learn-co-curriculum/react-events-in-detail-lab#8]
since this is brand new stuff i'm (and most people) are learning at this point, it would be helpful to see the code that we are writing render in the browser. 

Starting with this react lab, It appears the components you create don't render in the browser and i'm not sure if thats a sign of things to come in future labs.  The visual rendition and ability to console log stuff etc is important when testing to see if things work. Not having that ability is really not helpful - its kinda like driving a car but not being able to see through the windshield.

**Comment by Lukeghenco** [comment]
@bmolina-nyc we just updated this to use webpack, and should work flawlessly in the browser. Thanks for raising the issue.
