### ISSUE TITLE
cloned and ran $learn  / would not allow tests to run

### ISSUE THREAD

**Issue by rocketNeck** [learn-co-curriculum/react-events-in-detail-lab#9]
however $learn submit is working correctly

**Comment by rocketNeck** [comment]
> react-mouse-and-click-events@0.1.0 test /Users/jesselawson/Desktop/react-events-in-detail-lab-v-000
> mocha -R mocha-multi --require test/root.js --reporter-options nyan=-,json=.results.json

env: node\r: No such file or directory
npm ERR! Test failed.  See above for more details.
/Users/jesselawson/.rvm/gems/ruby-2.3.0/gems/learn-test-2.4.0/lib/learn_test/strategies/mocha.rb:49:in `results': undefined method `[]' for nil:NilClass (NoMethodError)

**Comment by Lukeghenco** [comment]
This should be working now with the latest PR. Thanks @rocketNeck
